name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: 
        dotnet build --no-restore

    - name: Publish
      run: 
        dotnet publish --no-build --configuration Release --output ./publish

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyArtifact
        path: ./publish